name: event_app
description: Companion app for orientation week and other events!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  english_words: ^3.1.5
  font_awesome_flutter: ^8.5.0
  gradient_bottom_navigation_bar: ^1.0.0+4
  intl: ^0.16.1
  flutter_svg: ^0.17.4
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400

  assets:
    - assets/images/
    - assets/icons/
